#ifndef __PLAYERWND_H__
#define __PLAYERWND_H__

// contorler base
#define IDC_WINDOW_BASE             100
#define IDC_STATIC_BASE             120
#define IDC_BUTTON_BASE             140
#define IDC_LISTVIEW_BASE           160
#define IDC_TRACKBAR_BASE           180

#define IDC_PLAYFILEPAGE_WINNOW             (IDC_WINDOW_BASE)

#define IDC_PLAYFILE_STATIC_PLAYTOOLBAR     (IDC_STATIC_BASE)
#define IDC_PLAYFILE_STATIC_GAP             (IDC_STATIC_BASE+1)
#define IDC_PLAYFILE_STATIC_DIR_NAME        (IDC_STATIC_BASE+2)
#define IDC_PLAYFILE_STATIC_SPEED_MODE      (IDC_STATIC_BASE+3)
#define IDC_PLAYFILE_STATIC_PLAY_TIME       (IDC_STATIC_BASE+4)
#define IDC_PLAYFILE_STATIC_VOLUME          (IDC_STATIC_BASE+5)
#define IDC_PLAYFILE_STATIC_FPS             (IDC_STATIC_BASE+6)

#define IDC_PLAYFILE_BUTTON_UPPER_DIR       (IDC_BUTTON_BASE)
#define IDC_PLAYFILE_BUTTON_PLAY_PAUSE      (IDC_BUTTON_BASE+1)
#define IDC_PLAYFILE_BUTTON_STOP            (IDC_BUTTON_BASE+2)
#define IDC_PLAYFILE_BUTTON_PLAY_SLOW       (IDC_BUTTON_BASE+3)
#define IDC_PLAYFILE_BUTTON_PLAY_FAST       (IDC_BUTTON_BASE+4)
#define IDC_PLAYFILE_BUTTON_VOICE_MUTE      (IDC_BUTTON_BASE+5)
#define IDC_PLAYFILE_BUTTON_MUSIC           (IDC_BUTTON_BASE+6)

#define IDC_PLAYFILE_LISTVIEW_FILELIST      (IDC_LISTVIEW_BASE)

#define IDC_PLAYFILE_TRACKBAR_PLAY_PROGRESS (IDC_TRACKBAR_BASE)
#define IDC_PLAYFILE_TRACKBAR_VOICE         (IDC_TRACKBAR_BASE+1)


#define MAINWND_W               1024
#define MAINWND_H               600


#endif